---
- hosts: localhost
  connection: local
  become: false

  tasks:
  - name: install packages
    package: 
      name: 
        - htop
        - tmux
        - vim-nox
        - zsh
        - micro
        - python3
        - python3-psutil
                
  - name: copy wallpaper file
    copy: 
      src: files/wallpaper.jpg
      dest: /usr/share/backgrounds/ansible-wallpaper.jpg
      owner: root
      group: root

  - name: set wallpaper
    dconf:
      key: "/org/gnome/desktop/background/picture-uri"
      value: "'file:///usr/share/backgrounds/ansible-wallpaper.jpg'"

  - name: set wallpaper position
    dconf:
      key: "/org/gnome/desktop/background/picture-options"
      value:  "'zoom'"        